config/routes.rb
Hackme::Application.routes.draw do
  resources :users
  resources :sessions
  resources :posts

  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  root :to => "posts#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Mass Assignment...
  # attr_accessible :username, :password
  validates :username, :presence => true, :uniqueness => true
  validates :password, :presence => true

  def self.authenticate(username, password)
    # SQL Injection...
    where( "username = '#{username}' AND password = '#{password}'" ).first
    # Consider something like this instead:
    # where( "username = ? AND password = ?", username, password ).first 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Cross-Site Request Forgery (CSRF)...
  # protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end  

  def edit
    @post = Post.find(params[:id])
  end
  
  def create
    @post = Post.new(params[:post])
    @post.user = current_user

    if @post.save
      redirect_to(@post, :notice => 'Post was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    # a user can update any post by
    # manipulating the URL
    @post = Post.find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to(@post, :notice => 'Post was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to(posts_url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackme</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%# Cross-Site Request Forgery... %>
  <%# csrf_meta_tag %>
</head>
<body>
<div id="usernav">
  <% if current_user %>
    Logged in as <%= current_user.username %> |
    <%= link_to "Log out", logout_path %>
  <% else %>
    <%= link_to "Sign up", signup_path %> |
    <%= link_to "Log in", login_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<p>
  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>
</p>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<% @posts.each do |post| %>
  <%# Using raw makes us vulnerable to XSS %>
  <h2><%= raw post.title %></h2>
  <p><i>By <%= post.user.try(:username) %></i></p>
  <p><%= raw post.body %></p>
  <p>
    <%= link_to 'Show', post %> |
    <%= link_to 'Edit', edit_post_path(post) %> |
    <%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %>
  </p>
<% end %>

<p><%= link_to 'New Post', new_post_path %></p>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<p><%= link_to 'Back', posts_path %></p>

app/views/posts/show.html.erb
<%# Using raw makes us vulnerable to XSS %>
<h1><%= raw @post.title %></h1>
<p><i>By <%= @post.user.try(:username) %></i></p>
<p><%= raw @post.body %></p>
<p>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<p><%= link_to 'Back', posts_path %></p>